version: "3.8"

services:
  
  mongo-user:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_USER}
      MONGO_INITDB_DATABASE: ${MONGO_USER}
    ports:
      - ${MONGO_USER_PORT}:27017
    volumes:
      - ./${MOONGO_USER_CONFIG}:/docker-entrypoint-initdb.d/initdb.js:ro

  mongo-course:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_COURSE}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_COURSE}
      MONGO_INITDB_DATABASE: ${MONGO_COURSE}
    ports:
      - ${MONGO_COURSE_PORT}:27017
    volumes:
      - ./${MOONGO_COURSE_CONFIG}:/docker-entrypoint-initdb.d/initdb.js:ro
  
  mongo-chapter:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_CHAPTER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_CHAPTER}
      MONGO_INITDB_DATABASE: ${MONGO_CHAPTER}
    ports:
      - ${MONGO_CHAPTER_PORT}:27017
    volumes:
      - ./${MOONGO_CHAPTER_CONFIG}:/docker-entrypoint-initdb.d/initdb.js:ro

  ms-user:
    image: ghcr.io/zth-app/ms-user:main
    restart: always
    depends_on:
      - mongo-user
    ports:
      - ${NEST_USER_PORT}:80
    environment:
      MONGO_URI_PROD: ${MONGO_USER_URI}
  
  ms-course:
    image: ghcr.io/zth-app/ms-course:main
    restart: always
    depends_on:
      - mongo-course
    ports:
      - ${NEST_COURSE_PORT}:80
    environment:
      MONGO_URI_PROD: ${MONGO_COURSE_URI}

  ms-chapter:
    image: ghcr.io/zth-app/ms-chapter:main
    restart: always
    depends_on:
      - mongo-chapter
    ports:
      - ${NEST_CHAPTER_PORT}:80
    environment:
      MONGO_URI_PROD: ${MONGO_CHAPTER_URI}